### PR TITLE
feature/branch-system: Implementation of Lua U SDK 'Branch-System'

### PR DESCRIPTION
**Pull request by 4x8Matrix**
# Context
As an additional option, at Datalink we've decided to implement a Flag-System which can be used to distinguish and identify different environments your games runtime is being executed under. 

As an example; A game might have multiple environments to support rigorous QA Analysis & Testing

- Production: The branch which contains the latest codebase for the production/final build
- Development: The branch which contains the codebase for the development/testing build

It's important that we not only support flexibility but that we acknowledge these environments so that the analytical data isn't too difficult to sift through once received. 

# This PR
- [✨ Added 'branchType' setting option to Datalink SDK](https://github.com/datalinkhq/rbx-datalink/commit/3a775c03cfeae5a511eefdd02e1b1ad3eae83d1c)
- [✨ Added HTTP Parameter for 'branch'](https://github.com/datalinkhq/rbx-datalink/commit/a5624f0af9eb28204fe3735d227f7dd43506a73c)
- [✨ Added additional HTTP Parameter into HTTP Component](https://github.com/datalinkhq/rbx-datalink/commit/b4bada00658fc5c775cd5c3bcc7e24a9ab617f5c)

# What's next
- Planning to implement an API to validate these branch types - waiting on @CompeyDev to validate everything is 👌 
- - `DatalinkInstance:isBranchAvaliableAsync(branchName: string) -> Promise`
- - `DatalinkInstance:switchToAvaliableBranch(branchName: string) -> Promise`
- - `DatalinkInstance:getActiveBranch(branchName: string) -> string`

**It's important that [THIS](https://github.com/datalinkhq/rbx-datalink/pull/3) pull request is merged before the [Development branch](https://github.com/datalinkhq/rbx-datalink/pull/1) is**

### CODE REVIEW

**Review by CompeyDev — APPROVED** [review]
👍 All clear! Should I merge this branch into the development branch, or directly into the main?

**Comment by 4x8Matrix** [comment]
@CompeyDev this branch should merge into development. 

Then development into 'main'

**Comment by 4x8Matrix** [comment]
An update! 

1 - This PR has been updated to support a `Branch-System` over a `Flag-System`, the naming was quite confusing
2 - This PR needs to be updated to support the latest structure changes, we need to maintain integrity of the codebase.

@CompeyDev has there been any progression on the server side flag system? This PR cannot be pushed until the server has acknowledged these changes.

I'm still waiting so I can implement this :- 

image

**Comment by CompeyDev** [comment]
Currently the backend does not include in forms of "branch systems", but I'm unsure whether that would be necessary. After all, don't branches just act as a form of "flow-control" on the SDK's end?  The flag system is currently fully functional with the endpoints as mentioned including: 
image

**Comment by 4x8Matrix** [comment]
The flag system itself is an entirely different system, it's my bad for confusing the two together and creating a somewhat confusing PR.

This is in regards to what branch the SDK is running on in retrospect to the environment it's ran under.

---

As an example; A game might have multiple environments to support rigorous QA Analysis & Testing

- Production: The branch which contains the latest codebase for the production/final build
- Development: The branch which contains the codebase for the development/testing build

We should support both environments.

**Comment by CompeyDev** [comment]
> an example; A game might have multiple environments to support rigoro

Ah, I understand. What endpoints would be required for a backend, and what kind of IO exchange would be taking place?

**Comment by 4x8Matrix** [comment]
Outdated PR, need to rewrite the branch system at a later date when the details have been settled.

**Pull request closed without merging**
